### PR TITLE
[aggregate] move report_id to shared_info

### PR DESCRIPTION
**Pull request by csharrison**
This will allow the aggregation service to dedupe duplicate reports.

### CODE REVIEW

**Comment by linnan-github** [comment]
LGTM.  Do we also expect other consumer API to have a unique report id? Thanks!

**Comment by csharrison** [comment]
> LGTM. Do we also expect other consumer API to have a unique report id? Thanks!

I would expect this field would be useful in other APIs that send delayed reports that we would want to have built-in support for retries.

**Review by linnan-github — APPROVED** [review]

**Comment by linnan-github** [comment]
Another question is for event-level report, the report id is just a unique id (GUID). Shall we be consistent with aggregatable report instead of enforcing it to be 64-bit unsigned integer?

**Comment by csharrison** [comment]
> Another question is for event-level report, the report id is just a unique id (GUID). Shall we be consistent with aggregatable report instead of enforcing it to be 64-bit unsigned integer?

Great point, just updated the CL to update this in both event and agg explainers. PTAL?

**Pull request merged**
